---
title: "tidy_data"
output:
  html_document:
    toc: true
    toc_float: true
author: Guojing Wu
data: 2018-09-25
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## section 1

### gather

```{r}
pulse_data = haven::read_sas("./data_import_examples/public_pulse_data.sas7bdat") %>%
  janitor::clean_names()
pulse_data
```

we can see this isn't a tidy data, for dbi is across 4 columns. So here we use `gather`:

```{r}
pulse_tidy = pulse_data %>%
  gather(key = "visit", value = "bdi", bdi_score_bl:bdi_score_12m)
pulse_tidy
```

### seperate

```{r}
pulse_df = 
  haven::read_sas("./data_import_examples/public_pulse_data.sas7bdat") %>%
  janitor::clean_names() %>%
  gather(key = visit, value = bdi, bdi_score_bl:bdi_score_12m) %>%
  separate(visit, into = c("remove_1", "remove_2", "visit"), sep = "_") %>%
  select(id, visit, everything(), -starts_with("remove")) %>%
  mutate(visit = replace(visit, visit == "bl", "00m"),
         visit = factor(visit, levels = str_c(c("00", "01", "06", "12"), "m"))) %>%
  arrange(id, visit)
pulse_df
```

### revisit the litter data
```{r}
litters_data = 
  read_csv("./data_import_examples/FAS_litters.csv", col_types = "ccddiiii") %>% 
  janitor::clean_names() %>%
  separate(group, into = c("dose", "day_of_tx"), sep = 3) %>%
  mutate(dose = tolower(dose),
         wt_gain = gd18_weight - gd0_weight) %>%
  arrange(litter_number)

litters_data
```

### data cleaning

```{r}
litters_data = 
  read_csv("./data_import_examples/FAS_litters.csv", col_types = "ccddiiii") %>% 
  janitor::clean_names() 
head(litters_data, 10)

litters_data %>%
  select(litter_number, ends_with("weight")) %>% 
  gather(key = gest_day, value = weight, gd0_weight:gd18_weight) %>% 
  mutate(gest_day = recode(gest_day, "gd0_weight" = 0, "gd18_weight" = 18))
```

### spread

```{r}
analysis_result = tibble(
  group = c("treatment", "treatment", "placebo", "placebo"),
  time = c("pre", "post", "pre", "post"),
  mean = c(4, 8, 3.5, 4)
)
analysis_result
```

now we see what will happen if we spread it:

```{r}
analysis_result %>%
  spread(key = time, value = mean)
```